### ISSUE TITLE
Why DPMSolverMultistepScheduler?

### ISSUE THREAD

**Issue by JoyHuYY1412** [ubc-vision/vivid123#6]
Thank you for the great work!

In the `generation_utils.py`, it seems that you switch the scheduler of zero123_pipe and video_xl to DPMSolverMultistepScheduler, am I correct about this? Is there any reason that you choose this design? I really appreciate your reply.

**Comment by jgkwak95** [comment]
Thanks for your attention :)

We empirically discovered that in our scenario of combining the two guidances from zero123 and video diffusion, dpmsolver performs better than ddim in terms of quality and stability.

**Comment by jgkwak95** [comment]
Thanks for your attention :)

We empirically discovered that in our scenario of combining the two guidances from zero123 and video diffusion, dpmsolver performs better than ddim in terms of quality and stability.
